CATEGORICAL:
- categories
- genres
- tags
IGNORE:
- app_id
- name
- release_date
- short_description
- tag_frequencies
TARGET: price
batch_size: 1000
batch_storage: raw_batches
best_model_path: results\model_results_20250410_234803\best_model.pkl
csv_file: games.csv
current_batch_number: 33
dataset_location: games.json
eda_storage: eda
encoders_path: results\model_results_20250410_234803\encoders.pkl
infer_folder: infer
max_duplicates: 0.05
max_missing: 0.1
max_outliers: 0.1
max_zeros: 0.1
output_dir: results
report_storage: reports
