CATEGORICAL:
- categories
- genres
- tags
IGNORE:
- app_id
- name
- release_date
- short_description
- tag_frequencies
TARGET: price
batch_size: 1000
batch_storage: storage/raw_batches
best_model_path: storage/results\model_results_20250512_000839\best_model.pkl
csv_file: storage/games.csv
current_batch_number: 12
dataset_location: storage/games.json
eda_storage: storage/results/eda
encoders_path: storage/results\model_results_20250512_000839\encoders.pkl
infer_folder: storage/results/infer
max_duplicates: 0.05
max_missing: 0.1
max_outliers: 0.1
max_zeros: 0.1
output_dir: storage/results
report_storage: storage/results/reports
