name: Train Model
on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
  pull_request:
    branches: [ main ]  # Trigger on PRs targeting main
  workflow_dispatch:    # Allow manual triggers
  schedule:
    - cron: '0 0 * * 1'  # Weekly (Monday at 00:00)

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install kaggle  # Required for Kaggle API
          pip install pyyaml # To work with config file
      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      - name: Download dataset via curl
        run: |
          curl -L -o steam-games-dataset.zip \
            -H "Authorization: Bearer ${{ secrets.KAGGLE_KEY }}" \
            "https://www.kaggle.com/api/v1/datasets/download/fronkongames/steam-games-dataset"
          unzip steam-games-dataset.zip -d storage/
          rm steam-games-dataset.zip
          rm storage/games.csv # some columns are written in the wrong format
      - name: Run update
        run: python run.py -mode update
      - name: Get model path from config
        id: model_path
        run: |
          python - <<EOF
          import yaml
          with open('options/config.yaml') as f:
              config = yaml.safe_load(f)
          print(f"MODEL_PATH={config['best_model_path']}")
          EOF >> $GITHUB_OUTPUT
      - name: Upload model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ${{ steps.model_path.outputs.MODEL_PATH }}