name: CI Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install kaggle  # Required for Kaggle API
      - name: Configure Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"'$KAGGLE_USERNAME'","key":"'$KAGGLE_KEY'"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
      - name: Download dataset via curl
        run: |
          curl -L -o steam-games-dataset.zip \
            -H "Authorization: Bearer ${{ secrets.KAGGLE_KEY }}" \
            "https://www.kaggle.com/api/v1/datasets/download/fronkongames/steam-games-dataset"
          unzip steam-games-dataset.zip -d storage/
          rm steam-games-dataset.zip
          rm storage/games.csv
    - name: Run tests
      run: pytest tests/ -v